language: python

matrix:
  include:
    - python: "2.7"
    - python: "3.5"
      env:
        - COVERAGE=1

cache: pip

install:
  - pip install -r requirements.txt
  - pip install pytest mock
  - if [[ "$COVERAGE" == 1 ]] && [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then
      pip install codecov pytest-cov
    ; fi

script:
  - if [[ "$COVERAGE" == 1 ]] && [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then
      pytest --cov-config=tests/.coveragerc --cov=. tests &&
      codecov
    ; else
      pytest
    ; fi